// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEW4TmwaxwwlJL3UMzNEOyApMIWSy8pE8',
    appId: '1:1340250550:web:895b0603e349c4d2b74917',
    messagingSenderId: '1340250550',
    projectId: 'flutter-ecommrce',
    authDomain: 'flutter-ecommrce.firebaseapp.com',
    databaseURL: 'https://flutter-ecommrce-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ecommrce.appspot.com',
    measurementId: 'G-2918LYJV19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsvXy1IlQMZLSCX3sgytDPXYoFxmBQdE',
    appId: '1:1340250550:android:0a76cf4c3130ebd8b74917',
    messagingSenderId: '1340250550',
    projectId: 'flutter-ecommrce',
    databaseURL: 'https://flutter-ecommrce-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ecommrce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmnTy6f8gr_H8ip753SA5oaYEaR3EBm5o',
    appId: '1:1340250550:ios:d49130eb507bdafbb74917',
    messagingSenderId: '1340250550',
    projectId: 'flutter-ecommrce',
    databaseURL: 'https://flutter-ecommrce-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ecommrce.appspot.com',
    androidClientId: '1340250550-6j9ukhvvoci2l2uhn4et9elideeoksru.apps.googleusercontent.com',
    iosClientId: '1340250550-78hk8vtpdkg63jb4kp583l3vmlf9lke0.apps.googleusercontent.com',
    iosBundleId: 'com.example.coworkplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmnTy6f8gr_H8ip753SA5oaYEaR3EBm5o',
    appId: '1:1340250550:ios:d49130eb507bdafbb74917',
    messagingSenderId: '1340250550',
    projectId: 'flutter-ecommrce',
    databaseURL: 'https://flutter-ecommrce-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ecommrce.firebasestorage.app',
    androidClientId: '1340250550-6j9ukhvvoci2l2uhn4et9elideeoksru.apps.googleusercontent.com',
    iosClientId: '1340250550-78hk8vtpdkg63jb4kp583l3vmlf9lke0.apps.googleusercontent.com',
    iosBundleId: 'com.example.coworkplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAadb2O2aYd_6kTvK12Sm19HvWjXgylF_s',
    appId: '1:1340250550:web:aa48ea52825bd486b74917',
    messagingSenderId: '1340250550',
    projectId: 'flutter-ecommrce',
    authDomain: 'flutter-ecommrce.firebaseapp.com',
    databaseURL: 'https://flutter-ecommrce-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ecommrce.appspot.com',
    measurementId: 'G-RWTWP66BE5',
  );
}
